# makefile for our implementation of NFA searching
# Files in folder:
#  Model.cpp - main file, constructs NFA, reads data and prints results
#   Node.h - Stucture for a node in the NFA
#   Pretty.h - Used for printing a NFA, used when -s flag is given at runtime
#   State.h - Used for matching the NFA, states holds positions in the NFA and the length of the match
#   World.h - The NFA structure, holds the nodes and keeps a start and end.
g++ -o nfa_search -std=c++0x Model.cpp -Ofast